from ._ots import lib as const_lib

OTS_MAX_ERROR_MESSAGE = const_lib.OTS_MAX_ERROR_MESSAGE
OTS_MAX_ERROR_CLASS = const_lib.OTS_MAX_ERROR_CLASS
OTS_MAX_VERSION_STRING = const_lib.OTS_MAX_VERSION_STRING
OTS_MONERO_SEED_WORDS = const_lib.OTS_MONERO_SEED_WORDS
OTS_POLYSEED_WORDS = const_lib.OTS_POLYSEED_WORDS
OTS_LEGACY_SEED_WORDS = const_lib.OTS_LEGACY_SEED_WORDS
