from ._ots import lib as _lib

OTS_MAX_ERROR_MESSAGE = _lib.OTS_MAX_ERROR_MESSAGE
OTS_MAX_ERROR_CLASS = _lib.OTS_MAX_ERROR_CLASS
OTS_MAX_VERSION_STRING = _lib.OTS_MAX_VERSION_STRING
OTS_MONERO_SEED_WORDS = _lib.OTS_MONERO_SEED_WORDS
OTS_POLYSEED_WORDS = _lib.OTS_POLYSEED_WORDS
OTS_LEGACY_SEED_WORDS = _lib.OTS_LEGACY_SEED_WORDS
