# THIS FILE IS AUTOGENERATED!
# DO NOT EDIT, THIS FILE WILL BE OVERRIDEN!


from .exception import OtsException


class OtsRuntimeError(OtsException):
    """
    C constant 'OTS_ERROR_RUNTIME_ERROR' with error code -1 in `ots-errors.h`.
    see ots::exception::RuntimeError in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsLogicError(OtsException):
    """
    C constant 'OTS_ERROR_LOGIC_ERROR' with error code -2 in `ots-errors.h`.
    see ots::exception::LogicError in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsInvalidArgumentException(OtsException):
    """
    C constant 'OTS_ERROR_INVALID_ARGUMENT' with error code -3 in `ots-errors.h`.
    see ots::exception::InvalidArgument in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsRangeError(OtsException):
    """
    C constant 'OTS_ERROR_RANGE_ERROR' with error code -4 in `ots-errors.h`.
    see ots::exception::RangeError in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsNotImplementedYetException(OtsException):
    """
    C constant 'OTS_ERROR_NOT_IMPLEMENTED_YET' with error code -5 in `ots-errors.h`.
    see ots::exception::NotImplementedYet in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsDomainError(OtsException):
    """
    C constant 'OTS_ERROR_DOMAIN_ERROR' with error code -6 in `ots-errors.h`.
    see ots::exception::DomainError in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsOutOfRangeException(OtsException):
    """
    C constant 'OTS_ERROR_OUT_OF_RANGE' with error code -7 in `ots-errors.h`.
    see ots::exception::OutOfRange in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsMemoryAllocationError(OtsException):
    """
    C constant 'OTS_ERROR_MEMORY_ALLOCATION_ERROR' with error code -11 in `ots-errors.h`.
    see ots::exception::MemoryAllocationError in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsSecurityError(OtsException):
    """
    C constant 'OTS_ERROR_SECURITY_ERROR' with error code -12 in `ots-errors.h`.
    see ots::exception::SecurityError in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsSecurityException(OtsException):
    """
    C constant 'OTS_ERROR_SECURITY_EXCEPTION' with error code -61 in `ots-errors.h`.
    see ots::exception::SecurityException in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsUnknownNetworkException(OtsException):
    """
    C constant 'OTS_ERROR_UNKNOWN_NETWORK' with error code -62 in `ots-errors.h`.
    see ots::exception::UnknownNetwork in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsBufferOverflowException(OtsException):
    """
    C constant 'OTS_ERROR_BUFFER_OVERFLOW_EXCEPTION' with error code -71 in `ots-errors.h`.
    see ots::exception::BufferOverflowException in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsLowEntropyException(OtsException):
    """
    C constant 'OTS_ERROR_LOW_ENTROPY' with error code -121 in `ots-errors.h`.
    see ots::exception::LowEntropy in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsWipeablestringUnsafeConversionException(OtsException):
    """
    C constant 'OTS_ERROR_WIPEABLESTRING_UNSAFE_CONVERSION' with error code -1001 in `ots-errors.h`.
    see ots::exception::wipeablestring::UnsafeConversion in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsWipeablevectorUnsafeConversionException(OtsException):
    """
    C constant 'OTS_ERROR_WIPEABLEVECTOR_UNSAFE_CONVERSION' with error code -2001 in `ots-errors.h`.
    see ots::exception::wipeablevector::UnsafeConversion in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsSignInvalidSignatureException(OtsException):
    """
    C constant 'OTS_ERROR_SIGN_INVALID_SIGNATURE' with error code -3001 in `ots-errors.h`.
    see ots::exception::sign::InvalidSignature in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsSignEmptyMessageException(OtsException):
    """
    C constant 'OTS_ERROR_SIGN_EMPTY_MESSAGE' with error code -3002 in `ots-errors.h`.
    see ots::exception::sign::EmptyMessage in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsSignEmptySignatureException(OtsException):
    """
    C constant 'OTS_ERROR_SIGN_EMPTY_SIGNATURE' with error code -3003 in `ots-errors.h`.
    see ots::exception::sign::EmptySignature in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsSeedNoDefaultLanguageSetException(OtsException):
    """
    C constant 'OTS_ERROR_SEED_NO_DEFAULT_LANGUAGE_SET' with error code -4001 in `ots-errors.h`.
    see ots::exception::seed::NoDefaultLanguageSet in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsSeedLanguageNotFoundException(OtsException):
    """
    C constant 'OTS_ERROR_SEED_LANGUAGE_NOT_FOUND' with error code -4002 in `ots-errors.h`.
    see ots::exception::seed::LanguageNotFound in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsSeedLanguageNotSupportedBySeedTypeException(OtsException):
    """
    C constant 'OTS_ERROR_SEED_LANGUAGE_NOT_SUPPORTED_BY_SEED_TYPE' with error code -4003 in `ots-errors.h`.
    see ots::exception::seed::LanguageNotSupportedBySeedType in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsSeedWordCountException(OtsException):
    """
    C constant 'OTS_ERROR_SEED_WORD_COUNT' with error code -4004 in `ots-errors.h`.
    see ots::exception::seed::WordCount in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsSeedSeedEncodingFailedException(OtsException):
    """
    C constant 'OTS_ERROR_SEED_SEED_ENCODING_FAILED' with error code -4005 in `ots-errors.h`.
    see ots::exception::seed::SeedEncodingFailed in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsSeedSeedDecodingFailedException(OtsException):
    """
    C constant 'OTS_ERROR_SEED_SEED_DECODING_FAILED' with error code -4006 in `ots-errors.h`.
    see ots::exception::seed::SeedDecodingFailed in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsSeedLengthMismatchException(OtsException):
    """
    C constant 'OTS_ERROR_SEED_LENGTH_MISMATCH' with error code -4007 in `ots-errors.h`.
    see ots::exception::seed::LengthMismatch in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsSeedTooFewValuesException(OtsException):
    """
    C constant 'OTS_ERROR_SEED_TOO_FEW_VALUES' with error code -4008 in `ots-errors.h`.
    see ots::exception::seed::TooFewValues in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsSeedPasswordNotSupportedException(OtsException):
    """
    C constant 'OTS_ERROR_SEED_PASSWORD_NOT_SUPPORTED' with error code -4009 in `ots-errors.h`.
    see ots::exception::seed::PasswordNotSupported in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsSeedMergeError(OtsException):
    """
    C constant 'OTS_ERROR_SEED_MERGE_ERROR' with error code -4010 in `ots-errors.h`.
    see ots::exception::seed::MergeError in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsPolyseedWordCountException(OtsException):
    """
    C constant 'OTS_ERROR_POLYSEED_WORD_COUNT' with error code -5001 in `ots-errors.h`.
    see ots::exception::polyseed::WordCount in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsPolyseedUnsupportedLanguageException(OtsException):
    """
    C constant 'OTS_ERROR_POLYSEED_UNSUPPORTED_LANGUAGE' with error code -5002 in `ots-errors.h`.
    see ots::exception::polyseed::UnsupportedLanguage in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsPolyseedChecksumMismatchException(OtsException):
    """
    C constant 'OTS_ERROR_POLYSEED_CHECKSUM_MISMATCH' with error code -5003 in `ots-errors.h`.
    see ots::exception::polyseed::ChecksumMismatch in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsPolyseedUnsupportedFeaturesException(OtsException):
    """
    C constant 'OTS_ERROR_POLYSEED_UNSUPPORTED_FEATURES' with error code -5004 in `ots-errors.h`.
    see ots::exception::polyseed::UnsupportedFeatures in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsPolyseedInvalidSeedFormatException(OtsException):
    """
    C constant 'OTS_ERROR_POLYSEED_INVALID_SEED_FORMAT' with error code -5005 in `ots-errors.h`.
    see ots::exception::polyseed::InvalidSeedFormat in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsPolyseedMemoryAllocationError(OtsException):
    """
    C constant 'OTS_ERROR_POLYSEED_MEMORY_ALLOCATION_ERROR' with error code -5006 in `ots-errors.h`.
    see ots::exception::polyseed::MemoryAllocationError in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsPolyseedAmbigousLanguageException(OtsException):
    """
    C constant 'OTS_ERROR_POLYSEED_AMBIGOUS_LANGUAGE' with error code -5007 in `ots-errors.h`.
    see ots::exception::polyseed::AmbigousLanguage in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsPolyseedNoPasswordProvidedException(OtsException):
    """
    C constant 'OTS_ERROR_POLYSEED_NO_PASSWORD_PROVIDED' with error code -5008 in `ots-errors.h`.
    see ots::exception::polyseed::NoPasswordProvided in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsLegacyseedInvalidSeedFormatException(OtsException):
    """
    C constant 'OTS_ERROR_LEGACYSEED_INVALID_SEED_FORMAT' with error code -6001 in `ots-errors.h`.
    see ots::exception::legacyseed::InvalidSeedFormat in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsSeedjarSeedNotFoundException(OtsException):
    """
    C constant 'OTS_ERROR_SEEDJAR_SEED_NOT_FOUND' with error code -7001 in `ots-errors.h`.
    see ots::exception::seedjar::SeedNotFound in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsKeystoreLockedAccessAttemptException(OtsException):
    """
    C constant 'OTS_ERROR_KEYSTORE_LOCKED_ACCESS_ATTEMPT' with error code -8001 in `ots-errors.h`.
    see ots::exception::keystore::LockedAccessAttempt in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsKeystoreLockedWriteAttemptException(OtsException):
    """
    C constant 'OTS_ERROR_KEYSTORE_LOCKED_WRITE_ATTEMPT' with error code -8002 in `ots-errors.h`.
    see ots::exception::keystore::LockedWriteAttempt in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsKeystorePolyseedActivePolyseedDataSessionException(OtsException):
    """
    C constant 'OTS_ERROR_KEYSTORE_POLYSEED_ACTIVE_POLYSEED_DATA_SESSION' with error code -8101 in `ots-errors.h`.
    see ots::exception::keystore::polyseed::ActivePolyseedDataSession in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsKeystorePolyseedNoActivePolyseedDataSessionException(OtsException):
    """
    C constant 'OTS_ERROR_KEYSTORE_POLYSEED_NO_ACTIVE_POLYSEED_DATA_SESSION' with error code -8102 in `ots-errors.h`.
    see ots::exception::keystore::polyseed::NoActivePolyseedDataSession in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsKeystorePolyseedPolyseedDataReadOnlySessionException(OtsException):
    """
    C constant 'OTS_ERROR_KEYSTORE_POLYSEED_POLYSEED_DATA_READ_ONLY_SESSION' with error code -8103 in `ots-errors.h`.
    see ots::exception::keystore::polyseed::PolyseedDataReadOnlySession in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsWalletAddressNotFoundException(OtsException):
    """
    C constant 'OTS_ERROR_WALLET_ADDRESS_NOT_FOUND' with error code -9001 in `ots-errors.h`.
    see ots::exception::wallet::AddressNotFound in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsWalletImportOutputsException(OtsException):
    """
    C constant 'OTS_ERROR_WALLET_IMPORT_OUTPUTS' with error code -9002 in `ots-errors.h`.
    see ots::exception::wallet::ImportOutputs in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsWalletExportKeyImagesException(OtsException):
    """
    C constant 'OTS_ERROR_WALLET_EXPORT_KEY_IMAGES' with error code -9003 in `ots-errors.h`.
    see ots::exception::wallet::ExportKeyImages in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsWalletUnsignedTransactionException(OtsException):
    """
    C constant 'OTS_ERROR_WALLET_UNSIGNED_TRANSACTION' with error code -9004 in `ots-errors.h`.
    see ots::exception::wallet::UnsignedTransaction in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsWalletInvalidCiphertextException(OtsException):
    """
    C constant 'OTS_ERROR_WALLET_INVALID_CIPHERTEXT' with error code -9005 in `ots-errors.h`.
    see ots::exception::wallet::InvalidCiphertext in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsWalletCiphertextAuthenticationFailedException(OtsException):
    """
    C constant 'OTS_ERROR_WALLET_CIPHERTEXT_AUTHENTICATION_FAILED' with error code -9006 in `ots-errors.h`.
    see ots::exception::wallet::CiphertextAuthenticationFailed in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsWalletInternalError(OtsException):
    """
    C constant 'OTS_ERROR_WALLET_INTERNAL_ERROR' with error code -9007 in `ots-errors.h`.
    see ots::exception::wallet::InternalError in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsAccountGenerationFailedException(OtsException):
    """
    C constant 'OTS_ERROR_ACCOUNT_GENERATION_FAILED' with error code -10001 in `ots-errors.h`.
    see ots::exception::account::GenerationFailed in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsTxInvalidException(OtsException):
    """
    C constant 'OTS_ERROR_TX_INVALID' with error code -11001 in `ots-errors.h`.
    see ots::exception::tx::Invalid in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsTxChangeException(OtsException):
    """
    C constant 'OTS_ERROR_TX_CHANGE' with error code -11002 in `ots-errors.h`.
    see ots::exception::tx::Change in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsTxParseException(OtsException):
    """
    C constant 'OTS_ERROR_TX_PARSE' with error code -11003 in `ots-errors.h`.
    see ots::exception::tx::Parse in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsTxSignException(OtsException):
    """
    C constant 'OTS_ERROR_TX_SIGN' with error code -11004 in `ots-errors.h`.
    see ots::exception::tx::Sign in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsTxUnlockTimeException(OtsException):
    """
    C constant 'OTS_ERROR_TX_UNLOCK_TIME' with error code -11005 in `ots-errors.h`.
    see ots::exception::tx::UnlockTime in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsTxConstructException(OtsException):
    """
    C constant 'OTS_ERROR_TX_CONSTRUCT' with error code -11006 in `ots-errors.h`.
    see ots::exception::tx::Construct in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsTxUnexpectedInputTypeException(OtsException):
    """
    C constant 'OTS_ERROR_TX_UNEXPECTED_INPUT_TYPE' with error code -11007 in `ots-errors.h`.
    see ots::exception::tx::UnexpectedInputType in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsAddressInvalidException(OtsException):
    """
    C constant 'OTS_ERROR_ADDRESS_INVALID' with error code -12001 in `ots-errors.h`.
    see ots::exception::address::Invalid in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsAddressNotIntegratedException(OtsException):
    """
    C constant 'OTS_ERROR_ADDRESS_NOT_INTEGRATED' with error code -12002 in `ots-errors.h`.
    see ots::exception::address::NotIntegrated in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsAddressNotStandardAddressException(OtsException):
    """
    C constant 'OTS_ERROR_ADDRESS_NOT_STANDARD_ADDRESS' with error code -12003 in `ots-errors.h`.
    see ots::exception::address::NotStandardAddress in `ots-exceptions.hpp` in the ots library.
    """
    pass


class OtsAddressInvalidPaymentIDException(OtsException):
    """
    C constant 'OTS_ERROR_ADDRESS_INVALID_PAYMENT_ID' with error code -12004 in `ots-errors.h`.
    see ots::exception::address::InvalidPaymentID in `ots-exceptions.hpp` in the ots library.
    """
    pass

EXCEPTION_MAPPING: dict[int, type] = {
    -1: OtsRuntimeError,
    -2: OtsLogicError,
    -3: OtsInvalidArgumentException,
    -4: OtsRangeError,
    -5: OtsNotImplementedYetException,
    -6: OtsDomainError,
    -7: OtsOutOfRangeException,
    -11: OtsMemoryAllocationError,
    -12: OtsSecurityError,
    -61: OtsSecurityException,
    -62: OtsUnknownNetworkException,
    -71: OtsBufferOverflowException,
    -121: OtsLowEntropyException,
    -1001: OtsWipeablestringUnsafeConversionException,
    -2001: OtsWipeablevectorUnsafeConversionException,
    -3001: OtsSignInvalidSignatureException,
    -3002: OtsSignEmptyMessageException,
    -3003: OtsSignEmptySignatureException,
    -4001: OtsSeedNoDefaultLanguageSetException,
    -4002: OtsSeedLanguageNotFoundException,
    -4003: OtsSeedLanguageNotSupportedBySeedTypeException,
    -4004: OtsSeedWordCountException,
    -4005: OtsSeedSeedEncodingFailedException,
    -4006: OtsSeedSeedDecodingFailedException,
    -4007: OtsSeedLengthMismatchException,
    -4008: OtsSeedTooFewValuesException,
    -4009: OtsSeedPasswordNotSupportedException,
    -4010: OtsSeedMergeError,
    -5001: OtsPolyseedWordCountException,
    -5002: OtsPolyseedUnsupportedLanguageException,
    -5003: OtsPolyseedChecksumMismatchException,
    -5004: OtsPolyseedUnsupportedFeaturesException,
    -5005: OtsPolyseedInvalidSeedFormatException,
    -5006: OtsPolyseedMemoryAllocationError,
    -5007: OtsPolyseedAmbigousLanguageException,
    -5008: OtsPolyseedNoPasswordProvidedException,
    -6001: OtsLegacyseedInvalidSeedFormatException,
    -7001: OtsSeedjarSeedNotFoundException,
    -8001: OtsKeystoreLockedAccessAttemptException,
    -8002: OtsKeystoreLockedWriteAttemptException,
    -8101: OtsKeystorePolyseedActivePolyseedDataSessionException,
    -8102: OtsKeystorePolyseedNoActivePolyseedDataSessionException,
    -8103: OtsKeystorePolyseedPolyseedDataReadOnlySessionException,
    -9001: OtsWalletAddressNotFoundException,
    -9002: OtsWalletImportOutputsException,
    -9003: OtsWalletExportKeyImagesException,
    -9004: OtsWalletUnsignedTransactionException,
    -9005: OtsWalletInvalidCiphertextException,
    -9006: OtsWalletCiphertextAuthenticationFailedException,
    -9007: OtsWalletInternalError,
    -10001: OtsAccountGenerationFailedException,
    -11001: OtsTxInvalidException,
    -11002: OtsTxChangeException,
    -11003: OtsTxParseException,
    -11004: OtsTxSignException,
    -11005: OtsTxUnlockTimeException,
    -11006: OtsTxConstructException,
    -11007: OtsTxUnexpectedInputTypeException,
    -12001: OtsAddressInvalidException,
    -12002: OtsAddressNotIntegratedException,
    -12003: OtsAddressNotStandardAddressException,
    -12004: OtsAddressInvalidPaymentIDException,
}