/**
 * @file ots-errors.h
 * @brief Error codes for the C ABI
 * @note Auto-generated from ots-exceptions.hpp - DO NOT EDIT DIRECTLY
 * @note Generated by gen-ots-error-header.cpp
 */

#ifndef OTS_ERRORS_H
#define OTS_ERRORS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Error codes matching C++ exceptions
 */
typedef enum {
    OTS_SUCCESS = 0,

    /**
     * @brief RuntimeError
     * @see ots::exception::RuntimeError in @see ots.hpp
     */
    OTS_ERROR_RUNTIME_ERROR = -1,

    /**
     * @brief LogicError
     * @see ots::exception::LogicError in @see ots.hpp
     */
    OTS_ERROR_LOGIC_ERROR = -2,

    /**
     * @brief InvalidArgument
     * @see ots::exception::InvalidArgument in @see ots.hpp
     */
    OTS_ERROR_INVALID_ARGUMENT = -3,

    /**
     * @brief RangeError
     * @see ots::exception::RangeError in @see ots.hpp
     */
    OTS_ERROR_RANGE_ERROR = -4,

    /**
     * @brief NotImplementedYet
     * @see ots::exception::NotImplementedYet in @see ots.hpp
     */
    OTS_ERROR_NOT_IMPLEMENTED_YET = -5,

    /**
     * @brief DomainError
     * @see ots::exception::DomainError in @see ots.hpp
     */
    OTS_ERROR_DOMAIN_ERROR = -6,

    /**
     * @brief OutOfRange
     * @see ots::exception::OutOfRange in @see ots.hpp
     */
    OTS_ERROR_OUT_OF_RANGE = -7,

    /**
     * @brief MemoryAllocationError
     * @see ots::exception::MemoryAllocationError in @see ots.hpp
     */
    OTS_ERROR_MEMORY_ALLOCATION_ERROR = -11,

    /**
     * @brief SecurityError
     * @see ots::exception::SecurityError in @see ots.hpp
     */
    OTS_ERROR_SECURITY_ERROR = -12,

    /**
     * @brief SecurityException
     * @see ots::exception::SecurityException in @see ots.hpp
     */
    OTS_ERROR_SECURITY_EXCEPTION = -61,

    /**
     * @brief UnknownNetwork
     * @see ots::exception::UnknownNetwork in @see ots.hpp
     */
    OTS_ERROR_UNKNOWN_NETWORK = -62,

    /**
     * @brief BufferOverflowException
     * @see ots::exception::BufferOverflowException in @see ots.hpp
     */
    OTS_ERROR_BUFFER_OVERFLOW_EXCEPTION = -71,

    /**
     * @brief LowEntropy
     * @see ots::exception::LowEntropy in @see ots.hpp
     */
    OTS_ERROR_LOW_ENTROPY = -121,

    /**
     * @brief UnsafeConversion
     * @see ots::exception::wipeablestring::UnsafeConversion in @see ots.hpp
     */
    OTS_ERROR_WIPEABLESTRING_UNSAFE_CONVERSION = -1001,

    /**
     * @brief UnsafeConversion
     * @see ots::exception::wipeablevector::UnsafeConversion in @see ots.hpp
     */
    OTS_ERROR_WIPEABLEVECTOR_UNSAFE_CONVERSION = -2001,

    /**
     * @brief InvalidSignature
     * @see ots::exception::sign::InvalidSignature in @see ots.hpp
     */
    OTS_ERROR_SIGN_INVALID_SIGNATURE = -3001,

    /**
     * @brief EmptyMessage
     * @see ots::exception::sign::EmptyMessage in @see ots.hpp
     */
    OTS_ERROR_SIGN_EMPTY_MESSAGE = -3002,

    /**
     * @brief EmptySignature
     * @see ots::exception::sign::EmptySignature in @see ots.hpp
     */
    OTS_ERROR_SIGN_EMPTY_SIGNATURE = -3003,

    /**
     * @brief NoDefaultLanguageSet
     * @see ots::exception::seed::NoDefaultLanguageSet in @see ots.hpp
     */
    OTS_ERROR_SEED_NO_DEFAULT_LANGUAGE_SET = -4001,

    /**
     * @brief LanguageNotFound
     * @see ots::exception::seed::LanguageNotFound in @see ots.hpp
     */
    OTS_ERROR_SEED_LANGUAGE_NOT_FOUND = -4002,

    /**
     * @brief LanguageNotSupportedBySeedType
     * @see ots::exception::seed::LanguageNotSupportedBySeedType in @see ots.hpp
     */
    OTS_ERROR_SEED_LANGUAGE_NOT_SUPPORTED_BY_SEED_TYPE = -4003,

    /**
     * @brief WordCount
     * @see ots::exception::seed::WordCount in @see ots.hpp
     */
    OTS_ERROR_SEED_WORD_COUNT = -4004,

    /**
     * @brief SeedEncodingFailed
     * @see ots::exception::seed::SeedEncodingFailed in @see ots.hpp
     */
    OTS_ERROR_SEED_SEED_ENCODING_FAILED = -4005,

    /**
     * @brief SeedDecodingFailed
     * @see ots::exception::seed::SeedDecodingFailed in @see ots.hpp
     */
    OTS_ERROR_SEED_SEED_DECODING_FAILED = -4006,

    /**
     * @brief LengthMismatch
     * @see ots::exception::seed::LengthMismatch in @see ots.hpp
     */
    OTS_ERROR_SEED_LENGTH_MISMATCH = -4007,

    /**
     * @brief TooFewValues
     * @see ots::exception::seed::TooFewValues in @see ots.hpp
     */
    OTS_ERROR_SEED_TOO_FEW_VALUES = -4008,

    /**
     * @brief PasswordNotSupported
     * @see ots::exception::seed::PasswordNotSupported in @see ots.hpp
     */
    OTS_ERROR_SEED_PASSWORD_NOT_SUPPORTED = -4009,

    /**
     * @brief MergeError
     * @see ots::exception::seed::MergeError in @see ots.hpp
     */
    OTS_ERROR_SEED_MERGE_ERROR = -4010,

    /**
     * @brief WordCount
     * @see ots::exception::polyseed::WordCount in @see ots.hpp
     */
    OTS_ERROR_POLYSEED_WORD_COUNT = -5001,

    /**
     * @brief UnsupportedLanguage
     * @see ots::exception::polyseed::UnsupportedLanguage in @see ots.hpp
     */
    OTS_ERROR_POLYSEED_UNSUPPORTED_LANGUAGE = -5002,

    /**
     * @brief ChecksumMismatch
     * @see ots::exception::polyseed::ChecksumMismatch in @see ots.hpp
     */
    OTS_ERROR_POLYSEED_CHECKSUM_MISMATCH = -5003,

    /**
     * @brief UnsupportedFeatures
     * @see ots::exception::polyseed::UnsupportedFeatures in @see ots.hpp
     */
    OTS_ERROR_POLYSEED_UNSUPPORTED_FEATURES = -5004,

    /**
     * @brief InvalidSeedFormat
     * @see ots::exception::polyseed::InvalidSeedFormat in @see ots.hpp
     */
    OTS_ERROR_POLYSEED_INVALID_SEED_FORMAT = -5005,

    /**
     * @brief MemoryAllocationError
     * @see ots::exception::polyseed::MemoryAllocationError in @see ots.hpp
     */
    OTS_ERROR_POLYSEED_MEMORY_ALLOCATION_ERROR = -5006,

    /**
     * @brief AmbigousLanguage
     * @see ots::exception::polyseed::AmbigousLanguage in @see ots.hpp
     */
    OTS_ERROR_POLYSEED_AMBIGOUS_LANGUAGE = -5007,

    /**
     * @brief NoPasswordProvided
     * @see ots::exception::polyseed::NoPasswordProvided in @see ots.hpp
     */
    OTS_ERROR_POLYSEED_NO_PASSWORD_PROVIDED = -5008,

    /**
     * @brief InvalidSeedFormat
     * @see ots::exception::legacyseed::InvalidSeedFormat in @see ots.hpp
     */
    OTS_ERROR_LEGACYSEED_INVALID_SEED_FORMAT = -6001,

    /**
     * @brief SeedNotFound
     * @see ots::exception::seedjar::SeedNotFound in @see ots.hpp
     */
    OTS_ERROR_SEEDJAR_SEED_NOT_FOUND = -7001,

    /**
     * @brief LockedAccessAttempt
     * @see ots::exception::keystore::LockedAccessAttempt in @see ots.hpp
     */
    OTS_ERROR_KEYSTORE_LOCKED_ACCESS_ATTEMPT = -8001,

    /**
     * @brief LockedWriteAttempt
     * @see ots::exception::keystore::LockedWriteAttempt in @see ots.hpp
     */
    OTS_ERROR_KEYSTORE_LOCKED_WRITE_ATTEMPT = -8002,

    /**
     * @brief ActivePolyseedDataSession
     * @see ots::exception::keystore::polyseed::ActivePolyseedDataSession in @see ots.hpp
     */
    OTS_ERROR_KEYSTORE_POLYSEED_ACTIVE_POLYSEED_DATA_SESSION = -8101,

    /**
     * @brief NoActivePolyseedDataSession
     * @see ots::exception::keystore::polyseed::NoActivePolyseedDataSession in @see ots.hpp
     */
    OTS_ERROR_KEYSTORE_POLYSEED_NO_ACTIVE_POLYSEED_DATA_SESSION = -8102,

    /**
     * @brief PolyseedDataReadOnlySession
     * @see ots::exception::keystore::polyseed::PolyseedDataReadOnlySession in @see ots.hpp
     */
    OTS_ERROR_KEYSTORE_POLYSEED_POLYSEED_DATA_READ_ONLY_SESSION = -8103,

    /**
     * @brief AddressNotFound
     * @see ots::exception::wallet::AddressNotFound in @see ots.hpp
     */
    OTS_ERROR_WALLET_ADDRESS_NOT_FOUND = -9001,

    /**
     * @brief ImportOutputs
     * @see ots::exception::wallet::ImportOutputs in @see ots.hpp
     */
    OTS_ERROR_WALLET_IMPORT_OUTPUTS = -9002,

    /**
     * @brief ExportKeyImages
     * @see ots::exception::wallet::ExportKeyImages in @see ots.hpp
     */
    OTS_ERROR_WALLET_EXPORT_KEY_IMAGES = -9003,

    /**
     * @brief UnsignedTransaction
     * @see ots::exception::wallet::UnsignedTransaction in @see ots.hpp
     */
    OTS_ERROR_WALLET_UNSIGNED_TRANSACTION = -9004,

    /**
     * @brief InvalidCiphertext
     * @see ots::exception::wallet::InvalidCiphertext in @see ots.hpp
     */
    OTS_ERROR_WALLET_INVALID_CIPHERTEXT = -9005,

    /**
     * @brief CiphertextAuthenticationFailed
     * @see ots::exception::wallet::CiphertextAuthenticationFailed in @see ots.hpp
     */
    OTS_ERROR_WALLET_CIPHERTEXT_AUTHENTICATION_FAILED = -9006,

    /**
     * @brief InternalError
     * @see ots::exception::wallet::InternalError in @see ots.hpp
     */
    OTS_ERROR_WALLET_INTERNAL_ERROR = -9007,

    /**
     * @brief GenerationFailed
     * @see ots::exception::account::GenerationFailed in @see ots.hpp
     */
    OTS_ERROR_ACCOUNT_GENERATION_FAILED = -10001,

    /**
     * @brief Invalid
     * @see ots::exception::tx::Invalid in @see ots.hpp
     */
    OTS_ERROR_TX_INVALID = -11001,

    /**
     * @brief Change
     * @see ots::exception::tx::Change in @see ots.hpp
     */
    OTS_ERROR_TX_CHANGE = -11002,

    /**
     * @brief Parse
     * @see ots::exception::tx::Parse in @see ots.hpp
     */
    OTS_ERROR_TX_PARSE = -11003,

    /**
     * @brief Sign
     * @see ots::exception::tx::Sign in @see ots.hpp
     */
    OTS_ERROR_TX_SIGN = -11004,

    /**
     * @brief UnlockTime
     * @see ots::exception::tx::UnlockTime in @see ots.hpp
     */
    OTS_ERROR_TX_UNLOCK_TIME = -11005,

    /**
     * @brief Construct
     * @see ots::exception::tx::Construct in @see ots.hpp
     */
    OTS_ERROR_TX_CONSTRUCT = -11006,

    /**
     * @brief UnexpectedInputType
     * @see ots::exception::tx::UnexpectedInputType in @see ots.hpp
     */
    OTS_ERROR_TX_UNEXPECTED_INPUT_TYPE = -11007,

    /**
     * @brief Invalid
     * @see ots::exception::address::Invalid in @see ots.hpp
     */
    OTS_ERROR_ADDRESS_INVALID = -12001,

    /**
     * @brief NotIntegrated
     * @see ots::exception::address::NotIntegrated in @see ots.hpp
     */
    OTS_ERROR_ADDRESS_NOT_INTEGRATED = -12002,

    /**
     * @brief NotStandardAddress
     * @see ots::exception::address::NotStandardAddress in @see ots.hpp
     */
    OTS_ERROR_ADDRESS_NOT_STANDARD_ADDRESS = -12003,

    /**
     * @brief InvalidPaymentID
     * @see ots::exception::address::InvalidPaymentID in @see ots.hpp
     */
    OTS_ERROR_ADDRESS_INVALID_PAYMENT_ID = -12004,

} OTS_ERROR_CODE;

#ifdef __cplusplus
}
#endif

#endif // OTS_ERRORS_H