from argparse import ArgumentParser, Namespace
from dataclasses import dataclass

@dataclass
class ExceptionMappingElement:
    error_code: int|None = None
    error_name: str|None = None
    name: str|None = None
    namespace: str|None = None

    @property
    def class_name(self) -> str:
        out: str = 'Ots' + ''.join([s[0].upper() + s[1:] for s in self.namespace.split('::')[2:]])
        return out if out.endswith('Error') or out.endswith('Exception') else f'{out}Exception'

class OtsExceptionGenerator:

    def __init__(self, values: Namespace):
        self.mapping: list[ExceptionMappingElement] = []
        self.values: Namespace = values

    def parse(self) -> None:
        with open(self.values.input, 'r') as f:
            lines: list[str] = f.readlines()
            f.close()
            line = 0
            while line < len(lines):
                if '@see' not in lines[line]:
                    line += 1
                    continue
                self.mapping.append(
                    ExceptionMappingElement(
                        error_code=int(lines[line + 2].split()[2][:-1]),
                        error_name=lines[line + 2].split()[0],
                        name=lines[line - 1].split()[2],
                        namespace=lines[line].split()[2]
                    )
                )
                line += 3

    def generate(self) -> None:
        if len(self.mapping) == 0:
            self.parse()
        out: list[str] = [
            '# THIS FILE IS AUTOGENERATED!\n# DO NOT EDIT, THIS FILE WILL BE OVERRIDEN!',
            'from .exception import OtsException'
        ]
        lookup: list[str] = ['EXCEPTION_MAPPING: dict[int, type] = {']
        for mapping in self.mapping:
            out.append(f'''
class {mapping.class_name}(OtsException):
    """
    C constant '{mapping.error_name}' with error code {mapping.error_code} in `ots-errors.h`.
    see {mapping.namespace} in `ots-exceptions.hpp` in the ots library.
    """
    pass
'''.strip())
            lookup.append(f"    {mapping.error_code}: {mapping.class_name},")
        lookup.append('}')
        with open(self.values.output, 'w') as f:
            f.write('\n\n\n'.join(out))
            f.write('\n\n')
            f.write('\n'.join(lookup))
            f.close()


if __name__ == '__main__':
    args: ArgumentParser = ArgumentParser(
        prog='Exception autogenerator',
        description='Generates Exception classes for ots errors, similar to ots Exception. Instead of the namespace, the class name will be prefixed')
    args.add_argument('input', type=str, help='ots-errors.h file')
    args.add_argument('output', type=str, help='destination, for the generated classes, probably ots_exceptions_generated.py')
    OtsExceptionGenerator(args.parse_args()).generate()
